name: SuperCraftBros
authors: [Double0negative, MCSG, NextInfinity]
version: 1.3.3
main: org.mcsg.double0negative.supercraftbros.SuperCraftBros
commands:
  scb:
    description: Super Craft Bros
    usage: /scb (command) (args)
    aliases: [scb]
